version: "2"

# A Docker Compose file for configuration of the production environment

services:
  lb:
    extends:
      file: docker-compose-common.yml
      service: lb

  app:
    extends:
      file: docker-compose-common.yml
      service: app
    image: etoews/idb_app
    expose:
      # Expose port 8000 so it's only visibile on the container, not the host
      - "8000"
    command: gunicorn app:app --bind 0.0.0.0:8000
      # Run Gunicorn to serve app requests

networks:
  backend: {}
